name: CI-CD Lambda API
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # for OIDC
      contents: read
    env:
      AWS_REGION: ${{ vars.AWS_REGION || 'us-east-1' }}
      AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN || secrets.AWS_ROLE_ARN }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest

      - name: Run tests
        run: pytest -q

      - name: Build Lambda artifact
        run: |
          rm -rf dist && mkdir -p dist
          pip install -r requirements.txt -t build
          cp -r *.py sudoku app.py lambda_handler.py build/ || true
          (cd build && zip -r ../dist/lambda.zip .)

      - name: Configure AWS creds (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_ARN }}

      - name: Install CDK
        run: npm i -g aws-cdk

      - name: CDK Synth & Deploy
        run: |
          cdk synth
          cdk deploy --require-approval never
